# Generated by tools/build_web_bundle.jl; do not edit by hand.
# Bundle schema: 1
# Source SHA-256: 4abd78c00f4cae721d2de54ef9f9fa155cf86367dd367c06bf07d7162c864b2d
# Source order:
# - src/types.jl
# - src/indexing.jl
# - src/shifts.jl
# - src/web_rng.jl
# - src/initialization.jl
# - src/observables.jl
# - src/metropolis.jl
# - src/webapi.jl

# BEGIN src/types.jl
abstract type Abstractfields end
abstract type AbstractGaugefields{NC,Dim} <: Abstractfields end
abstract type Gaugefields_4D{NC} <: AbstractGaugefields{NC,4} end

"""
    Gaugefields_4D_nowing(NC, NX, NY, NZ, NT; NDW=0)

Allocate a serial four-dimensional gauge field backed by a six-dimensional
`Array{ComplexF64,6}` with layout `(color, color, x, y, z, t)`.

GaugefieldsLite currently accepts `NC = 2` or `NC = 3` and does not allocate
wing/halo cells, so `NDW` must be zero.
"""
struct Gaugefields_4D_nowing{NC} <: Gaugefields_4D{NC}
    U::Array{ComplexF64,6}
    NX::Int64
    NY::Int64
    NZ::Int64
    NT::Int64
    NDW::Int64
    NV::Int64
    NC::Int64
end

function _validated_color_count(NC::Integer)
    nc = Int64(NC)
    if nc != 2 && nc != 3
        throw(ArgumentError("NC must be 2 or 3, received $NC"))
    end
    return nc
end

function _validated_extent(name::String, extent::Integer)
    value = Int64(extent)
    if value <= 0
        throw(ArgumentError("$name must be positive, received $extent"))
    end
    return value
end

function _validated_ndw(NDW::Integer)
    ndw = Int64(NDW)
    if ndw != 0
        throw(ArgumentError("GaugefieldsLite currently requires NDW = 0, received $NDW"))
    end
    return ndw
end

function Gaugefields_4D_nowing(
    NC::Integer,
    NX::Integer,
    NY::Integer,
    NZ::Integer,
    NT::Integer;
    NDW::Integer=0,
)
    nc = _validated_color_count(NC)
    nx = _validated_extent("NX", NX)
    ny = _validated_extent("NY", NY)
    nz = _validated_extent("NZ", NZ)
    nt = _validated_extent("NT", NT)
    ndw = _validated_ndw(NDW)
    data = zeros(ComplexF64, nc, nc, nx, ny, nz, nt)
    return Gaugefields_4D_nowing{nc}(data, nx, ny, nz, nt, ndw, nx * ny * nz * nt, nc)
end

"""
    Gaugefields_4D_nowing(data; NDW=0)

Wrap an existing six-dimensional `Array{ComplexF64,6}` without copying it.
The first two dimensions must be equal and identify a supported color count.
"""
function Gaugefields_4D_nowing(data::Array{ComplexF64,6}; NDW::Integer=0)
    nc1, nc2, nx0, ny0, nz0, nt0 = size(data)
    if nc1 != nc2
        throw(DimensionMismatch("the first two storage dimensions must be equal, received $nc1 and $nc2"))
    end

    nc = _validated_color_count(nc1)
    nx = _validated_extent("NX", nx0)
    ny = _validated_extent("NY", ny0)
    nz = _validated_extent("NZ", nz0)
    nt = _validated_extent("NT", nt0)
    ndw = _validated_ndw(NDW)
    return Gaugefields_4D_nowing{nc}(data, nx, ny, nz, nt, ndw, nx * ny * nz * nt, nc)
end
# END src/types.jl

# BEGIN src/indexing.jl
Base.size(field::Gaugefields_4D_nowing) = size(field.U)
Base.size(field::Gaugefields_4D_nowing, dimension::Integer) = size(field.U, dimension)
Base.length(field::Gaugefields_4D_nowing) = length(field.U)

function Base.getindex(field::Gaugefields_4D_nowing, i, j, x, y, z, t)
    return getindex(field.U, i, j, x, y, z, t)
end

function Base.setindex!(field::Gaugefields_4D_nowing, value, i, j, x, y, z, t)
    setindex!(field.U, value, i, j, x, y, z, t)
    return field
end

function Base.similar(field::Gaugefields_4D_nowing)
    return Gaugefields_4D_nowing(
        field.NC,
        field.NX,
        field.NY,
        field.NZ,
        field.NT;
        NDW=field.NDW,
    )
end

function _require_compatible_fields(
    destination::Gaugefields_4D_nowing,
    source::Gaugefields_4D_nowing,
)
    if size(destination) != size(source)
        throw(DimensionMismatch("gauge-field storage shapes must match"))
    end
    return nothing
end

function clear_U!(field::Gaugefields_4D_nowing)
    for t in 1:field.NT
        for z in 1:field.NZ
            for y in 1:field.NY
                for x in 1:field.NX
                    for j in 1:field.NC
                        for i in 1:field.NC
                            setindex!(field.U, 0.0 + 0.0im, i, j, x, y, z, t)
                        end
                    end
                end
            end
        end
    end
    return field
end

function unit_U!(field::Gaugefields_4D_nowing)
    for t in 1:field.NT
        for z in 1:field.NZ
            for y in 1:field.NY
                for x in 1:field.NX
                    for j in 1:field.NC
                        for i in 1:field.NC
                            value = ifelse(i == j, 1.0 + 0.0im, 0.0 + 0.0im)
                            setindex!(field.U, value, i, j, x, y, z, t)
                        end
                    end
                end
            end
        end
    end
    return field
end

function substitute_U!(
    destination::Gaugefields_4D_nowing,
    source::Gaugefields_4D_nowing,
)
    _require_compatible_fields(destination, source)
    for t in 1:destination.NT
        for z in 1:destination.NZ
            for y in 1:destination.NY
                for x in 1:destination.NX
                    for j in 1:destination.NC
                        for i in 1:destination.NC
                            value = getindex(source.U, i, j, x, y, z, t)
                            setindex!(destination.U, value, i, j, x, y, z, t)
                        end
                    end
                end
            end
        end
    end
    return destination
end

function add_U!(destination::Gaugefields_4D_nowing, source::Gaugefields_4D_nowing)
    return add_U!(destination, 1.0, source)
end

function add_U!(
    destination::Gaugefields_4D_nowing,
    alpha::Number,
    source::Gaugefields_4D_nowing,
)
    _require_compatible_fields(destination, source)
    for t in 1:destination.NT
        for z in 1:destination.NZ
            for y in 1:destination.NY
                for x in 1:destination.NX
                    for j in 1:destination.NC
                        for i in 1:destination.NC
                            old_value = getindex(destination.U, i, j, x, y, z, t)
                            source_value = getindex(source.U, i, j, x, y, z, t)
                            setindex!(
                                destination.U,
                                old_value + alpha * source_value,
                                i,
                                j,
                                x,
                                y,
                                z,
                                t,
                            )
                        end
                    end
                end
            end
        end
    end
    return destination
end

function Base.copy(field::Gaugefields_4D_nowing)
    result = similar(field)
    substitute_U!(result, field)
    return result
end

function similar_gaugefields(fields::Vector{T}) where {T<:Gaugefields_4D_nowing}
    result = Vector{T}(undef, length(fields))
    for index in 1:length(fields)
        result[index] = similar(fields[index])
    end
    return result
end

set_wing_U!(::Gaugefields_4D_nowing) = nothing
getvalue(field::Gaugefields_4D_nowing, i, j, x, y, z, t) = field[i, j, x, y, z, t]
get_myrank(::Gaugefields_4D_nowing) = 0
get_nprocs(::Gaugefields_4D_nowing) = 1
barrier(::Gaugefields_4D_nowing) = nothing
# END src/indexing.jl

# BEGIN src/shifts.jl
"""
    Adjoint_Gaugefields(parent)

A read-only lazy adjoint view. Color indices are transposed and values are
complex-conjugated when an element is read.
"""
struct Adjoint_Gaugefields{T<:Abstractfields} <: Abstractfields
    parent::T
end

Base.adjoint(field::T) where {T<:Abstractfields} = Adjoint_Gaugefields{T}(field)
Base.adjoint(field::Adjoint_Gaugefields) = field.parent
Base.parent(field::Adjoint_Gaugefields) = field.parent
Base.size(field::Adjoint_Gaugefields) = size(field.parent)
Base.size(field::Adjoint_Gaugefields, dimension::Integer) = size(field.parent, dimension)
Base.length(field::Adjoint_Gaugefields) = length(field.parent)

function Base.getindex(field::Adjoint_Gaugefields, i, j, x, y, z, t)
    return conj(field.parent[j, i, x, y, z, t])
end

"""
    Shifted_Gaugefields_4D_nowing(parent, shift)

A read-only lazy periodic-shift view. A value requested at lattice coordinate
`x` is read from `x + shift`, with every coordinate wrapped periodically.
"""
struct Shifted_Gaugefields_4D_nowing{NC} <: Abstractfields
    parent::Gaugefields_4D_nowing{NC}
    shift::NTuple{4,Int64}
end

Base.size(field::Shifted_Gaugefields_4D_nowing) = size(field.parent)
Base.size(field::Shifted_Gaugefields_4D_nowing, dimension::Integer) =
    size(field.parent, dimension)
Base.length(field::Shifted_Gaugefields_4D_nowing) = length(field.parent)
Base.parent(field::Shifted_Gaugefields_4D_nowing) = field.parent

function _periodic_coordinate(index::Integer, shift::Integer, extent::Integer)
    return mod(index - 1 + shift, extent) + 1
end

function Base.getindex(field::Shifted_Gaugefields_4D_nowing, i, j, x, y, z, t)
    parent = field.parent
    shifted_x = _periodic_coordinate(x, field.shift[1], parent.NX)
    shifted_y = _periodic_coordinate(y, field.shift[2], parent.NY)
    shifted_z = _periodic_coordinate(z, field.shift[3], parent.NZ)
    shifted_t = _periodic_coordinate(t, field.shift[4], parent.NT)
    return parent[i, j, shifted_x, shifted_y, shifted_z, shifted_t]
end

function _validated_shift(shift::Tuple)
    if length(shift) != 4
        throw(ArgumentError("shift must contain exactly four coordinates"))
    end
    for coordinate in shift
        if !(coordinate isa Integer)
            throw(ArgumentError("every shift coordinate must be an integer"))
        end
    end
    return (Int64(shift[1]), Int64(shift[2]), Int64(shift[3]), Int64(shift[4]))
end

function _direction_shift(direction::Integer)
    if direction == 0 || abs(direction) > 4
        throw(ArgumentError("shift direction must be one of -4:-1 or 1:4, received $direction"))
    end

    sign = ifelse(direction > 0, Int64(1), Int64(-1))
    axis = abs(direction)
    shift = if axis == 1
        (sign, Int64(0), Int64(0), Int64(0))
    elseif axis == 2
        (Int64(0), sign, Int64(0), Int64(0))
    elseif axis == 3
        (Int64(0), Int64(0), sign, Int64(0))
    else
        (Int64(0), Int64(0), Int64(0), sign)
    end
    return shift
end

function shift_U(field::Gaugefields_4D_nowing{NC}, direction::Integer) where {NC}
    return Shifted_Gaugefields_4D_nowing{NC}(field, _direction_shift(direction))
end

function shift_U(
    field::Gaugefields_4D_nowing{NC},
    shift::Tuple,
) where {NC}
    return Shifted_Gaugefields_4D_nowing{NC}(field, _validated_shift(shift))
end

function shift_U(field::Shifted_Gaugefields_4D_nowing, direction::Integer)
    return shift_U(field, _direction_shift(direction))
end

function shift_U(
    field::Shifted_Gaugefields_4D_nowing,
    shift::Tuple,
)
    additional_shift = _validated_shift(shift)
    combined_shift = (
        field.shift[1] + additional_shift[1],
        field.shift[2] + additional_shift[2],
        field.shift[3] + additional_shift[3],
        field.shift[4] + additional_shift[4],
    )
    return shift_U(field.parent, combined_shift)
end
# END src/shifts.jl

# BEGIN src/web_rng.jl
const WEB_RNG_MODULUS = Int64(2147483647)
const WEB_RNG_MULTIPLIER = Int64(48271)
const WEB_RNG_MASK = Int64(4294967295)

function _web_rng_next(state::Int64)
    next_state = xor(state, (state << 13) & WEB_RNG_MASK)
    next_state = xor(next_state, next_state >> 17)
    return xor(next_state, (next_state << 5) & WEB_RNG_MASK)
end

function web_rng_state(seed::Integer)
    if seed < 0
        throw(ArgumentError("seed must be nonnegative"))
    end
    return Int64[mod(Int64(seed), WEB_RNG_MASK) + 1]
end

function restore_web_rng_state(value::Integer)
    state = Int64(value)
    if state <= 0 || state > WEB_RNG_MASK
        throw(ArgumentError("web RNG state must be in 1:$WEB_RNG_MASK"))
    end
    return Int64[state]
end

function web_rand!(state::Vector{Int64})
    if length(state) != 1 || state[1] <= 0 || state[1] > WEB_RNG_MASK
        throw(ArgumentError("web RNG state must contain one valid integer"))
    end
    next_state = _web_rng_next(state[1])
    state[1] = next_state
    return (next_state - 1) / Float64(WEB_RNG_MASK)
end

function web_standard_normal_pair!(state::Vector{Int64})
    first_uniform = web_rand!(state)
    while first_uniform <= 0.0
        first_uniform = web_rand!(state)
    end
    radius = sqrt(-2.0 * log(first_uniform))
    angle = 2.0 * pi * web_rand!(state)
    return radius * cos(angle), radius * sin(angle)
end
# END src/web_rng.jl

# BEGIN src/initialization.jl
using Random

function _matrix_determinant(matrix::AbstractMatrix, nc::Integer)
    if nc == 2
        return matrix[1, 1] * matrix[2, 2] - matrix[1, 2] * matrix[2, 1]
    elseif nc == 3
        return matrix[1, 1] * (matrix[2, 2] * matrix[3, 3] - matrix[2, 3] * matrix[3, 2]) -
               matrix[1, 2] * (matrix[2, 1] * matrix[3, 3] - matrix[2, 3] * matrix[3, 1]) +
               matrix[1, 3] * (matrix[2, 1] * matrix[3, 2] - matrix[2, 2] * matrix[3, 1])
    end
    throw(ArgumentError("matrix color count must be 2 or 3, received $nc"))
end

function _require_color_matrix(matrix::AbstractMatrix)
    rows, columns = size(matrix)
    if rows != columns || (rows != 2 && rows != 3)
        throw(DimensionMismatch("color matrix must have shape 2×2 or 3×3"))
    end
    return rows
end

function normalizeN!(matrix::AbstractMatrix)
    nc = _require_color_matrix(matrix)
    for column in 1:nc
        for previous in 1:(column - 1)
            projection = 0.0 + 0.0im
            for row in 1:nc
                projection += conj(matrix[row, previous]) * matrix[row, column]
            end
            for row in 1:nc
                matrix[row, column] -= projection * matrix[row, previous]
            end
        end

        norm_squared = 0.0
        for row in 1:nc
            norm_squared += abs2(matrix[row, column])
        end
        if norm_squared <= 1.0e-28
            throw(ArgumentError("matrix columns are linearly dependent"))
        end
        inverse_norm = inv(sqrt(norm_squared))
        for row in 1:nc
            matrix[row, column] *= inverse_norm
        end
    end

    determinant = _matrix_determinant(matrix, nc)
    determinant_magnitude = abs(determinant)
    if determinant_magnitude <= 1.0e-14
        throw(ArgumentError("matrix determinant is numerically zero"))
    end
    phase_correction = conj(determinant) / determinant_magnitude
    for row in 1:nc
        matrix[row, 1] *= phase_correction
    end
    return matrix
end

normalize2!(matrix::AbstractMatrix) = normalizeN!(matrix)
normalize3!(matrix::AbstractMatrix) = normalizeN!(matrix)

function _standard_normal_pair()
    first_uniform = rand()
    while first_uniform <= 0.0
        first_uniform = rand()
    end
    radius = sqrt(-2.0 * log(first_uniform))
    angle = 2.0 * pi * rand()
    return radius * cos(angle), radius * sin(angle)
end

function _haar_su_matrix!(matrix::AbstractMatrix)
    nc = _require_color_matrix(matrix)
    for column in 1:nc
        for row in 1:nc
            real_part, imaginary_part = _standard_normal_pair()
            matrix[row, column] = ComplexF64(real_part, imaginary_part)
        end
    end
    normalizeN!(matrix)
    return matrix
end

function normalize_U!(field::Gaugefields_4D_nowing)
    matrix = zeros(ComplexF64, field.NC, field.NC)
    for t in 1:field.NT
        for z in 1:field.NZ
            for y in 1:field.NY
                for x in 1:field.NX
                    for j in 1:field.NC
                        for i in 1:field.NC
                            matrix[i, j] = field[i, j, x, y, z, t]
                        end
                    end
                    normalizeN!(matrix)
                    for j in 1:field.NC
                        for i in 1:field.NC
                            field[i, j, x, y, z, t] = matrix[i, j]
                        end
                    end
                end
            end
        end
    end
    return field
end

function identityGaugefields_4D_nowing(NC, NX, NY, NZ, NT; verbose_level=0)
    if !(verbose_level isa Integer)
        throw(ArgumentError("verbose_level must be an integer"))
    end
    field = Gaugefields_4D_nowing(NC, NX, NY, NZ, NT)
    unit_U!(field)
    return field
end

function randomGaugefields_4D_nowing(
    NC,
    NX,
    NY,
    NZ,
    NT;
    verbose_level=0,
    randomnumber="Random",
    seed=nothing,
)
    if !(verbose_level isa Integer)
        throw(ArgumentError("verbose_level must be an integer"))
    end
    random_mode = String(randomnumber)
    if random_mode != "Random" && random_mode != "Reproducible"
        throw(ArgumentError("randomnumber must be \"Random\" or \"Reproducible\""))
    end
    if seed !== nothing
        if !(seed isa Integer)
            throw(ArgumentError("seed must be an integer or nothing"))
        end
        Random.seed!(seed)
    elseif random_mode == "Reproducible"
        Random.seed!(123)
    end

    field = Gaugefields_4D_nowing(NC, NX, NY, NZ, NT)
    matrix = zeros(ComplexF64, field.NC, field.NC)
    for t in 1:field.NT
        for z in 1:field.NZ
            for y in 1:field.NY
                for x in 1:field.NX
                    _haar_su_matrix!(matrix)
                    for j in 1:field.NC
                        for i in 1:field.NC
                            field[i, j, x, y, z, t] = matrix[i, j]
                        end
                    end
                end
            end
        end
    end
    return field
end

IdentityGauges_4D(NC, NX, NY, NZ, NT; kwargs...) =
    identityGaugefields_4D_nowing(NC, NX, NY, NZ, NT; kwargs...)
RandomGauges_4D(NC, NX, NY, NZ, NT; kwargs...) =
    randomGaugefields_4D_nowing(NC, NX, NY, NZ, NT; kwargs...)

function IdentityGauges(NC, NDW, NN...; kwargs...)
    _validated_ndw(NDW)
    if length(NN) != 4
        throw(ArgumentError("GaugefieldsLite supports exactly four lattice dimensions"))
    end
    return IdentityGauges_4D(NC, NN...; kwargs...)
end

function RandomGauges(NC, NDW, NN...; kwargs...)
    _validated_ndw(NDW)
    if length(NN) != 4
        throw(ArgumentError("GaugefieldsLite supports exactly four lattice dimensions"))
    end
    return RandomGauges_4D(NC, NN...; kwargs...)
end

function _validate_serial_options(
    mpi,
    PEs,
    mpiinit,
    cuda,
    blocks,
    accelerator,
    singleprecision,
    isMPILattice,
    boundarycondition,
)
    if mpi != false || PEs !== nothing || (mpiinit !== nothing && mpiinit != false)
        throw(ArgumentError("GaugefieldsLite supports serial execution only"))
    end
    if cuda != false || blocks !== nothing || !(accelerator == "none" || accelerator == :none)
        throw(ArgumentError("GaugefieldsLite does not support accelerator options"))
    end
    if singleprecision != false || isMPILattice != false
        throw(ArgumentError("GaugefieldsLite supports ComplexF64 serial fields only"))
    end
    if boundarycondition !== nothing
        if length(boundarycondition) != 4
            throw(ArgumentError("boundarycondition must contain four entries"))
        end
        for value in boundarycondition
            if value != 1
                throw(ArgumentError("GaugefieldsLite currently supports periodic boundaries only"))
            end
        end
    end
    return nothing
end

function Initialize_Gaugefields(
    NC,
    NDW,
    NN...;
    condition="cold",
    mpi=false,
    PEs=nothing,
    mpiinit=nothing,
    verbose_level=0,
    randomnumber="Random",
    cuda=false,
    blocks=nothing,
    accelerator="none",
    singleprecision=false,
    isMPILattice=false,
    boundarycondition=nothing,
    seed=nothing,
)
    _validated_ndw(NDW)
    if length(NN) != 4
        throw(ArgumentError("GaugefieldsLite supports exactly four lattice dimensions"))
    end
    _validate_serial_options(
        mpi,
        PEs,
        mpiinit,
        cuda,
        blocks,
        accelerator,
        singleprecision,
        isMPILattice,
        boundarycondition,
    )

    condition_name = lowercase(String(condition))
    if condition_name != "cold" && condition_name != "hot" && condition_name != "random"
        throw(ArgumentError("condition must be \"cold\", \"hot\", or \"random\""))
    end
    random_mode = String(randomnumber)
    if random_mode != "Random" && random_mode != "Reproducible"
        throw(ArgumentError("randomnumber must be \"Random\" or \"Reproducible\""))
    end
    if seed !== nothing && !(seed isa Integer)
        throw(ArgumentError("seed must be an integer or nothing"))
    end

    if condition_name != "cold"
        if seed !== nothing
            Random.seed!(seed)
        elseif random_mode == "Reproducible"
            Random.seed!(123)
        end
    end

    prototype = Gaugefields_4D_nowing(NC, NN...)
    fields = Vector{typeof(prototype)}(undef, 4)
    for direction in 1:4
        if condition_name == "cold"
            fields[direction] = identityGaugefields_4D_nowing(
                NC,
                NN...;
                verbose_level=verbose_level,
            )
        else
            fields[direction] = randomGaugefields_4D_nowing(
                NC,
                NN...;
                verbose_level=verbose_level,
                randomnumber="Random",
            )
        end
    end
    return fields
end

function Initialize_4DGaugefields(NC, NDW, NN...; kwargs...)
    if length(NN) != 4
        throw(ArgumentError("Initialize_4DGaugefields requires four lattice extents"))
    end
    return Initialize_Gaugefields(NC, NDW, NN...; kwargs...)
end
# END src/initialization.jl

# BEGIN src/observables.jl
function _require_configuration(fields::Vector)
    if length(fields) != 4
        throw(DimensionMismatch("a four-dimensional configuration must contain four link fields"))
    end
    reference = fields[1]
    if !(reference isa Gaugefields_4D_nowing)
        throw(ArgumentError("configuration entries must be Gaugefields_4D_nowing fields"))
    end
    for direction in 2:4
        field = fields[direction]
        if !(field isa Gaugefields_4D_nowing) || size(field) != size(reference)
            throw(DimensionMismatch("all four link fields must have the same color and lattice shape"))
        end
    end
    return reference
end

function _shifted_coordinates(x, y, z, t, direction::Integer, step::Integer, reference)
    if direction == 1
        x = _periodic_coordinate(x, step, reference.NX)
    elseif direction == 2
        y = _periodic_coordinate(y, step, reference.NY)
    elseif direction == 3
        z = _periodic_coordinate(z, step, reference.NZ)
    elseif direction == 4
        t = _periodic_coordinate(t, step, reference.NT)
    else
        throw(ArgumentError("direction must be in 1:4"))
    end
    return x, y, z, t
end

function _plaquette_site_generic_unchecked(fields, reference, mu, nu, x, y, z, t)
    xmu, ymu, zmu, tmu = _shifted_coordinates(x, y, z, t, mu, 1, reference)
    xnu, ynu, znu, tnu = _shifted_coordinates(x, y, z, t, nu, 1, reference)

    total = 0.0 + 0.0im
    for i in 1:reference.NC
        for j in 1:reference.NC
            first = fields[mu][i, j, x, y, z, t]
            for k in 1:reference.NC
                second = fields[nu][j, k, xmu, ymu, zmu, tmu]
                for l in 1:reference.NC
                    third = conj(fields[mu][l, k, xnu, ynu, znu, tnu])
                    fourth = conj(fields[nu][i, l, x, y, z, t])
                    total += first * second * third * fourth
                end
            end
        end
    end
    return total
end

function _plaquette_site_su2_unchecked(fields, reference, mu, nu, x, y, z, t)
    xmu, ymu, zmu, tmu = _shifted_coordinates(x, y, z, t, mu, 1, reference)
    xnu, ynu, znu, tnu = _shifted_coordinates(x, y, z, t, nu, 1, reference)

    a11 = fields[mu][1, 1, x, y, z, t]
    a12 = fields[mu][1, 2, x, y, z, t]
    a21 = fields[mu][2, 1, x, y, z, t]
    a22 = fields[mu][2, 2, x, y, z, t]
    b11 = fields[nu][1, 1, xmu, ymu, zmu, tmu]
    b12 = fields[nu][1, 2, xmu, ymu, zmu, tmu]
    b21 = fields[nu][2, 1, xmu, ymu, zmu, tmu]
    b22 = fields[nu][2, 2, xmu, ymu, zmu, tmu]
    c11 = fields[mu][1, 1, xnu, ynu, znu, tnu]
    c12 = fields[mu][1, 2, xnu, ynu, znu, tnu]
    c21 = fields[mu][2, 1, xnu, ynu, znu, tnu]
    c22 = fields[mu][2, 2, xnu, ynu, znu, tnu]
    d11 = fields[nu][1, 1, x, y, z, t]
    d12 = fields[nu][1, 2, x, y, z, t]
    d21 = fields[nu][2, 1, x, y, z, t]
    d22 = fields[nu][2, 2, x, y, z, t]

    ab11 = a11 * b11 + a12 * b21
    ab12 = a11 * b12 + a12 * b22
    ab21 = a21 * b11 + a22 * b21
    ab22 = a21 * b12 + a22 * b22
    dc11 = d11 * c11 + d12 * c21
    dc12 = d11 * c12 + d12 * c22
    dc21 = d21 * c11 + d22 * c21
    dc22 = d21 * c12 + d22 * c22
    return ab11 * conj(dc11) + ab12 * conj(dc12) +
           ab21 * conj(dc21) + ab22 * conj(dc22)
end

function _plaquette_site_unchecked(fields, reference, mu, nu, x, y, z, t)
    if reference.NC == 2
        return _plaquette_site_su2_unchecked(fields, reference, mu, nu, x, y, z, t)
    end
    return _plaquette_site_generic_unchecked(fields, reference, mu, nu, x, y, z, t)
end

function plaquette_site(fields::Vector, mu::Integer, nu::Integer, x, y, z, t)
    reference = _require_configuration(fields)
    if mu < 1 || mu > 4 || nu < 1 || nu > 4 || mu == nu
        throw(ArgumentError("plaquette directions must be distinct values in 1:4"))
    end
    return _plaquette_site_unchecked(fields, reference, mu, nu, x, y, z, t)
end

function forward_staple_site!(
    output::AbstractMatrix,
    fields::Vector,
    mu::Integer,
    nu::Integer,
    x,
    y,
    z,
    t,
)
    reference = _require_configuration(fields)
    if mu == nu || mu < 1 || mu > 4 || nu < 1 || nu > 4
        throw(ArgumentError("staple directions must be distinct values in 1:4"))
    end
    if size(output) != (reference.NC, reference.NC)
        throw(DimensionMismatch("staple output has the wrong color shape"))
    end
    xmu, ymu, zmu, tmu = _shifted_coordinates(x, y, z, t, mu, 1, reference)
    xnu, ynu, znu, tnu = _shifted_coordinates(x, y, z, t, nu, 1, reference)
    for j in 1:reference.NC
        for i in 1:reference.NC
            value = 0.0 + 0.0im
            for k in 1:reference.NC
                for l in 1:reference.NC
                    value += fields[nu][i, k, xmu, ymu, zmu, tmu] *
                             conj(fields[mu][l, k, xnu, ynu, znu, tnu]) *
                             conj(fields[nu][j, l, x, y, z, t])
                end
            end
            output[i, j] = value
        end
    end
    return output
end

function backward_staple_site!(
    output::AbstractMatrix,
    fields::Vector,
    mu::Integer,
    nu::Integer,
    x,
    y,
    z,
    t,
)
    reference = _require_configuration(fields)
    if mu == nu || mu < 1 || mu > 4 || nu < 1 || nu > 4
        throw(ArgumentError("staple directions must be distinct values in 1:4"))
    end
    if size(output) != (reference.NC, reference.NC)
        throw(DimensionMismatch("staple output has the wrong color shape"))
    end
    xminusnu, yminusnu, zminusnu, tminusnu =
        _shifted_coordinates(x, y, z, t, nu, -1, reference)
    xmunu, ymunu, zmunu, tmunu =
        _shifted_coordinates(xminusnu, yminusnu, zminusnu, tminusnu, mu, 1, reference)
    for j in 1:reference.NC
        for i in 1:reference.NC
            value = 0.0 + 0.0im
            for k in 1:reference.NC
                for l in 1:reference.NC
                    value += conj(fields[nu][k, i, xmunu, ymunu, zmunu, tmunu]) *
                             conj(fields[mu][l, k, xminusnu, yminusnu, zminusnu, tminusnu]) *
                             fields[nu][l, j, xminusnu, yminusnu, zminusnu, tminusnu]
                end
            end
            output[i, j] = value
        end
    end
    return output
end

function construct_staple!(
    staple::Gaugefields_4D_nowing,
    fields::Vector,
    mu::Integer,
    temporary::Gaugefields_4D_nowing,
)
    reference = _require_configuration(fields)
    if mu < 1 || mu > 4
        throw(ArgumentError("staple direction must be in 1:4"))
    end
    _require_compatible_fields(staple, reference)
    _require_compatible_fields(temporary, reference)
    first_term = true
    for nu in 1:4
        if nu == mu
            continue
        end
        mul!(temporary, fields[nu], shift_U(fields[mu], nu))
        beta = ifelse(first_term, 0, 1)
        mul!(staple, temporary, shift_U(fields[nu], mu)', 1, beta)
        first_term = false
    end
    return staple
end

function calculate_Plaquette(
    fields::Vector,
    temporary::Gaugefields_4D_nowing,
    staple::Gaugefields_4D_nowing,
)
    reference = _require_configuration(fields)
    _require_compatible_fields(temporary, reference)
    _require_compatible_fields(staple, reference)
    total = 0.0
    for mu in 1:4
        construct_staple!(staple, fields, mu, temporary)
        mul!(temporary, fields[mu], staple')
        total += real(tr(temporary))
    end
    return 0.5 * total
end

function calculate_Plaquette(fields::Vector, temporaries::Vector)
    if length(temporaries) < 2
        throw(ArgumentError("calculate_Plaquette requires at least two temporary fields"))
    end
    return calculate_Plaquette(fields, temporaries[1], temporaries[2])
end

function calculate_Plaquette(fields::Vector)
    reference = _require_configuration(fields)
    total = 0.0
    for t in 1:reference.NT
        for z in 1:reference.NZ
            for y in 1:reference.NY
                for x in 1:reference.NX
                    for mu in 1:3
                        for nu in (mu + 1):4
                            total += real(
                                _plaquette_site_unchecked(
                                    fields,
                                    reference,
                                    mu,
                                    nu,
                                    x,
                                    y,
                                    z,
                                    t,
                                ),
                            )
                        end
                    end
                end
            end
        end
    end
    return total
end

function normalized_plaquette(fields::Vector)
    reference = _require_configuration(fields)
    return calculate_Plaquette(fields) / (6.0 * reference.NV * reference.NC)
end

function gauge_transform!(destination::Vector, fields::Vector, transformation::Gaugefields_4D_nowing)
    reference = _require_configuration(fields)
    _require_configuration(destination)
    _require_compatible_fields(transformation, reference)
    for direction in 1:4
        _require_compatible_fields(destination[direction], reference)
        if destination[direction] === fields[direction]
            throw(ArgumentError("gauge_transform! destination must not alias the source"))
        end
        for t in 1:reference.NT
            for z in 1:reference.NZ
                for y in 1:reference.NY
                    for x in 1:reference.NX
                        xs, ys, zs, ts =
                            _shifted_coordinates(x, y, z, t, direction, 1, reference)
                        for j in 1:reference.NC
                            for i in 1:reference.NC
                                value = 0.0 + 0.0im
                                for k in 1:reference.NC
                                    for l in 1:reference.NC
                                        value += transformation[i, k, x, y, z, t] *
                                                 fields[direction][k, l, x, y, z, t] *
                                                 conj(transformation[j, l, xs, ys, zs, ts])
                                    end
                                end
                                destination[direction][i, j, x, y, z, t] = value
                            end
                        end
                    end
                end
            end
        end
    end
    return destination
end

function calculate_Polyakov_loop(
    fields::Vector,
    temporary1::Gaugefields_4D_nowing,
    temporary2::Gaugefields_4D_nowing,
)
    reference = _require_configuration(fields)
    _require_compatible_fields(temporary1, reference)
    _require_compatible_fields(temporary2, reference)
    substitute_U!(temporary1, fields[4])
    old_product = temporary1
    new_product = temporary2
    for time_offset in 1:(reference.NT - 1)
        shifted_time_links = shift_U(fields[4], (0, 0, 0, time_offset))
        mul_skiplastindex!(new_product, old_product, shifted_time_links)
        old_product, new_product = new_product, old_product
    end
    spatial_volume = reference.NX * reference.NY * reference.NZ
    return partial_tr(old_product, 4) / (reference.NC * spatial_volume)
end

function calculate_Polyakov_loop(fields::Vector)
    reference = _require_configuration(fields)
    if reference.NC == 2
        total = 0.0 + 0.0im
        for z in 1:reference.NZ
            for y in 1:reference.NY
                for x in 1:reference.NX
                    product11 = 1.0 + 0.0im
                    product12 = 0.0 + 0.0im
                    product21 = 0.0 + 0.0im
                    product22 = 1.0 + 0.0im
                    for t in 1:reference.NT
                        link11 = fields[4][1, 1, x, y, z, t]
                        link12 = fields[4][1, 2, x, y, z, t]
                        link21 = fields[4][2, 1, x, y, z, t]
                        link22 = fields[4][2, 2, x, y, z, t]
                        next11 = product11 * link11 + product12 * link21
                        next12 = product11 * link12 + product12 * link22
                        next21 = product21 * link11 + product22 * link21
                        next22 = product21 * link12 + product22 * link22
                        product11 = next11
                        product12 = next12
                        product21 = next21
                        product22 = next22
                    end
                    total += product11 + product22
                end
            end
        end
        spatial_volume = reference.NX * reference.NY * reference.NZ
        return total / (2 * spatial_volume)
    end

    total = 0.0 + 0.0im
    for z in 1:reference.NZ
        for y in 1:reference.NY
            for x in 1:reference.NX
                product11 = 1.0 + 0.0im
                product12 = 0.0 + 0.0im
                product13 = 0.0 + 0.0im
                product21 = 0.0 + 0.0im
                product22 = 1.0 + 0.0im
                product23 = 0.0 + 0.0im
                product31 = 0.0 + 0.0im
                product32 = 0.0 + 0.0im
                product33 = 1.0 + 0.0im
                for t in 1:reference.NT
                    link11 = fields[4][1, 1, x, y, z, t]
                    link12 = fields[4][1, 2, x, y, z, t]
                    link13 = fields[4][1, 3, x, y, z, t]
                    link21 = fields[4][2, 1, x, y, z, t]
                    link22 = fields[4][2, 2, x, y, z, t]
                    link23 = fields[4][2, 3, x, y, z, t]
                    link31 = fields[4][3, 1, x, y, z, t]
                    link32 = fields[4][3, 2, x, y, z, t]
                    link33 = fields[4][3, 3, x, y, z, t]
                    next11 = product11 * link11 + product12 * link21 + product13 * link31
                    next12 = product11 * link12 + product12 * link22 + product13 * link32
                    next13 = product11 * link13 + product12 * link23 + product13 * link33
                    next21 = product21 * link11 + product22 * link21 + product23 * link31
                    next22 = product21 * link12 + product22 * link22 + product23 * link32
                    next23 = product21 * link13 + product22 * link23 + product23 * link33
                    next31 = product31 * link11 + product32 * link21 + product33 * link31
                    next32 = product31 * link12 + product32 * link22 + product33 * link32
                    next33 = product31 * link13 + product32 * link23 + product33 * link33
                    product11 = next11
                    product12 = next12
                    product13 = next13
                    product21 = next21
                    product22 = next22
                    product23 = next23
                    product31 = next31
                    product32 = next32
                    product33 = next33
                end
                total += product11 + product22 + product33
            end
        end
    end
    spatial_volume = reference.NX * reference.NY * reference.NZ
    return total / (3 * spatial_volume)
end

function _local_plaquette_energy_unchecked(fields, reference, x, y, z, t)
    total = 0.0
    for mu in 1:3
        for nu in (mu + 1):4
            total += 1.0 -
                     real(_plaquette_site_unchecked(fields, reference, mu, nu, x, y, z, t)) /
                     reference.NC
        end
    end
    return total
end

function local_plaquette_energy(fields::Vector, x, y, z, t)
    reference = _require_configuration(fields)
    return _local_plaquette_energy_unchecked(fields, reference, x, y, z, t)
end

function _plane_axes(plane)
    name = lowercase(String(plane))
    if name == "xy"
        return 1, 2, 3, 4
    elseif name == "xz"
        return 1, 3, 2, 4
    elseif name == "xt"
        return 1, 4, 2, 3
    elseif name == "yz"
        return 2, 3, 1, 4
    elseif name == "yt"
        return 2, 4, 1, 3
    elseif name == "zt"
        return 3, 4, 1, 2
    end
    throw(ArgumentError("plane must be one of xy, xz, xt, yz, yt, or zt"))
end

function _lattice_extents(reference)
    return (reference.NX, reference.NY, reference.NZ, reference.NT)
end

function slice_shape(fields::Vector, plane)
    reference = _require_configuration(fields)
    first_axis, second_axis, _, _ = _plane_axes(plane)
    extents = _lattice_extents(reference)
    return extents[first_axis], extents[second_axis]
end

function _validated_slice(slice, first_fixed_axis, second_fixed_axis, extents)
    if !(slice isa Tuple) || length(slice) != 2
        throw(ArgumentError("slice must be a tuple containing two fixed coordinates"))
    end
    first_coordinate = slice[1]
    second_coordinate = slice[2]
    if !(first_coordinate isa Integer) || !(second_coordinate isa Integer)
        throw(ArgumentError("slice coordinates must be integers"))
    end
    if first_coordinate < 1 || first_coordinate > extents[first_fixed_axis] ||
       second_coordinate < 1 || second_coordinate > extents[second_fixed_axis]
        throw(BoundsError(extents, slice))
    end
    return Int(first_coordinate), Int(second_coordinate)
end

function local_plaquette_energy!(output::AbstractVector, fields::Vector, plane, slice)
    reference = _require_configuration(fields)
    first_axis, second_axis, first_fixed_axis, second_fixed_axis = _plane_axes(plane)
    extents = _lattice_extents(reference)
    width = extents[first_axis]
    height = extents[second_axis]
    if length(output) != width * height
        throw(DimensionMismatch("slice output length must equal width × height"))
    end
    first_fixed, second_fixed =
        _validated_slice(slice, first_fixed_axis, second_fixed_axis, extents)

    for second_coordinate in 1:height
        for first_coordinate in 1:width
            coordinates = [1, 1, 1, 1]
            coordinates[first_axis] = first_coordinate
            coordinates[second_axis] = second_coordinate
            coordinates[first_fixed_axis] = first_fixed
            coordinates[second_fixed_axis] = second_fixed
            output[(second_coordinate - 1) * width + first_coordinate] =
                _local_plaquette_energy_unchecked(
                    fields,
                    reference,
                    coordinates[1],
                    coordinates[2],
                    coordinates[3],
                    coordinates[4],
                )
        end
    end
    return output
end

function local_plaquette_energy!(output::AbstractVector, fields::Vector, plane, slice::Integer)
    return local_plaquette_energy!(output, fields, plane, (slice, slice))
end

function local_slice_result(fields::Vector, plane, slice)
    width, height = slice_shape(fields, plane)
    output = zeros(Float64, width * height)
    local_plaquette_energy!(output, fields, plane, slice)
    result = Vector{Float64}(undef, 2 + length(output))
    result[1] = width
    result[2] = height
    for index in 1:length(output)
        result[index + 2] = output[index]
    end
    return result
end
# END src/observables.jl

# BEGIN src/metropolis.jl
using Random

abstract type AbstractGaugeUpdater end

struct MetropolisUpdater <: AbstractGaugeUpdater
    beta::Float64
    epsilon::Float64

    function MetropolisUpdater(beta::Real, epsilon::Real)
        beta_value = Float64(beta)
        epsilon_value = Float64(epsilon)
        if !isfinite(beta_value) || beta_value < 0.0
            throw(ArgumentError("beta must be finite and nonnegative"))
        end
        if !isfinite(epsilon_value) || epsilon_value <= 0.0 || epsilon_value > 1.0
            throw(ArgumentError("epsilon must satisfy 0 < epsilon <= 1"))
        end
        return new(beta_value, epsilon_value)
    end
end

struct MetropolisWorkspace
    su2::Matrix{ComplexF64}
    embedded::Matrix{ComplexF64}
    old_link::Matrix{ComplexF64}
    proposed_link::Matrix{ComplexF64}
    staple::Matrix{ComplexF64}
    forward::Matrix{ComplexF64}
    backward::Matrix{ComplexF64}
end

function MetropolisWorkspace(nc::Integer=3)
    color_count = _validated_color_count(nc)
    return MetropolisWorkspace(
        zeros(ComplexF64, 2, 2),
        zeros(ComplexF64, color_count, color_count),
        zeros(ComplexF64, color_count, color_count),
        zeros(ComplexF64, color_count, color_count),
        zeros(ComplexF64, color_count, color_count),
        zeros(ComplexF64, color_count, color_count),
        zeros(ComplexF64, color_count, color_count),
    )
end

struct MetropolisLinkResult
    accepted::Bool
    delta_action::Float64
end

struct MetropolisSweepResult
    accepted::Int64
    offered::Int64
    acceptance_rate::Float64
end

struct MetropolisHistory
    plaquette::Vector{Float64}
    polyakov::Vector{ComplexF64}
    acceptance::Vector{Float64}
    accepted::Int64
    offered::Int64
end

function _require_matrix_shape(matrix::AbstractMatrix, rows, columns, name)
    if size(matrix) != (rows, columns)
        throw(DimensionMismatch("$name must have shape $rows×$columns"))
    end
    return nothing
end

function make_near_identity_su2!(
    proposal::AbstractMatrix,
    a1::Real,
    a2::Real,
    a3::Real,
)
    _require_matrix_shape(proposal, 2, 2, "SU(2) proposal")
    radius_squared = Float64(a1)^2 + Float64(a2)^2 + Float64(a3)^2
    if !isfinite(radius_squared) || radius_squared > 1.0
        throw(ArgumentError("proposal vector must satisfy |a| <= 1"))
    end
    a0 = sqrt(max(0.0, 1.0 - radius_squared))
    proposal[1, 1] = a0 + im * a3
    proposal[1, 2] = a2 + im * a1
    proposal[2, 1] = -a2 + im * a1
    proposal[2, 2] = a0 - im * a3
    return proposal
end

function _random_uniform(rng)
    if rng === nothing
        return rand()
    elseif rng isa Vector{Int64}
        return web_rand!(rng)
    end
    return rand(rng)
end

function make_near_identity_su2!(proposal::AbstractMatrix, epsilon::Real, rng)
    epsilon_value = Float64(epsilon)
    if !isfinite(epsilon_value) || epsilon_value <= 0.0 || epsilon_value > 1.0
        throw(ArgumentError("epsilon must satisfy 0 < epsilon <= 1"))
    end
    while true
        a1 = epsilon_value * (2.0 * _random_uniform(rng) - 1.0)
        a2 = epsilon_value * (2.0 * _random_uniform(rng) - 1.0)
        a3 = epsilon_value * (2.0 * _random_uniform(rng) - 1.0)
        if a1^2 + a2^2 + a3^2 < epsilon_value^2
            return make_near_identity_su2!(proposal, a1, a2, a3)
        end
    end
end

make_near_identity_su2!(proposal::AbstractMatrix, epsilon::Real) =
    make_near_identity_su2!(proposal, epsilon, nothing)

function _color_pair(pair::Integer)
    if pair == 1
        return 1, 2
    elseif pair == 2
        return 2, 3
    elseif pair == 3
        return 1, 3
    end
    throw(ArgumentError("SU(3) subgroup pair must be 1, 2, or 3"))
end

function embed_su2_in_su3!(embedded::AbstractMatrix, proposal::AbstractMatrix, pair::Integer)
    _require_matrix_shape(embedded, 3, 3, "embedded proposal")
    _require_matrix_shape(proposal, 2, 2, "SU(2) proposal")
    first_color, second_color = _color_pair(pair)
    fill!(embedded, 0.0 + 0.0im)
    for color in 1:3
        embedded[color, color] = 1.0 + 0.0im
    end
    embedded[first_color, first_color] = proposal[1, 1]
    embedded[first_color, second_color] = proposal[1, 2]
    embedded[second_color, first_color] = proposal[2, 1]
    embedded[second_color, second_color] = proposal[2, 2]
    return embedded
end

function _small_matrix_multiply!(output, left, right, nc)
    for j in 1:nc
        for i in 1:nc
            value = 0.0 + 0.0im
            for k in 1:nc
                value += left[i, k] * right[k, j]
            end
            output[i, j] = value
        end
    end
    return output
end

function propose_link_su3!(
    proposed_link::AbstractMatrix,
    old_link::AbstractMatrix,
    su2_proposal::AbstractMatrix,
    pair::Integer,
    embedded::AbstractMatrix,
)
    _require_matrix_shape(proposed_link, 3, 3, "proposed link")
    _require_matrix_shape(old_link, 3, 3, "old link")
    embed_su2_in_su3!(embedded, su2_proposal, pair)
    return _small_matrix_multiply!(proposed_link, embedded, old_link, 3)
end

function propose_link_su3!(proposed_link, old_link, su2_proposal, pair::Integer)
    embedded = zeros(ComplexF64, 3, 3)
    return propose_link_su3!(proposed_link, old_link, su2_proposal, pair, embedded)
end

function _copy_link_to_matrix!(matrix, field, x, y, z, t)
    for j in 1:field.NC
        for i in 1:field.NC
            matrix[i, j] = field[i, j, x, y, z, t]
        end
    end
    return matrix
end

function _write_matrix_to_link!(field, matrix, x, y, z, t)
    for j in 1:field.NC
        for i in 1:field.NC
            field[i, j, x, y, z, t] = matrix[i, j]
        end
    end
    return field
end

function local_wilson_staple_site!(
    staple::AbstractMatrix,
    fields::Vector,
    mu::Integer,
    x,
    y,
    z,
    t,
    forward::AbstractMatrix,
    backward::AbstractMatrix,
)
    reference = _require_configuration(fields)
    nc = reference.NC
    _require_matrix_shape(staple, nc, nc, "Wilson staple")
    _require_matrix_shape(forward, nc, nc, "forward staple workspace")
    _require_matrix_shape(backward, nc, nc, "backward staple workspace")
    fill!(staple, 0.0 + 0.0im)
    for nu in 1:4
        if nu == mu
            continue
        end
        forward_staple_site!(forward, fields, mu, nu, x, y, z, t)
        backward_staple_site!(backward, fields, mu, nu, x, y, z, t)
        for j in 1:nc
            for i in 1:nc
                staple[i, j] += forward[i, j] + backward[i, j]
            end
        end
    end
    return staple
end

function local_wilson_staple_site!(staple, fields, mu, x, y, z, t)
    reference = _require_configuration(fields)
    forward = zeros(ComplexF64, reference.NC, reference.NC)
    backward = zeros(ComplexF64, reference.NC, reference.NC)
    return local_wilson_staple_site!(staple, fields, mu, x, y, z, t, forward, backward)
end

function local_action_from_staple(link::AbstractMatrix, staple::AbstractMatrix, beta::Real)
    rows, columns = size(link)
    if rows != columns || size(staple) != size(link)
        throw(DimensionMismatch("link and staple must be square matrices of the same shape"))
    end
    trace_product = 0.0 + 0.0im
    for i in 1:rows
        for j in 1:rows
            trace_product += link[i, j] * staple[j, i]
        end
    end
    return -(Float64(beta) / rows) * real(trace_product)
end

function wilson_action(fields::Vector, beta::Real)
    reference = _require_configuration(fields)
    return Float64(beta) * (6.0 * reference.NV - calculate_Plaquette(fields) / reference.NC)
end

function _affected_plaquette_sum_unchecked(fields, reference, mu, x, y, z, t)
    total = 0.0
    for nu in 1:4
        if nu == mu
            continue
        end
        first_direction = min(mu, nu)
        second_direction = max(mu, nu)
        total += real(
            _plaquette_site_unchecked(
                fields,
                reference,
                first_direction,
                second_direction,
                x,
                y,
                z,
                t,
            ),
        )
        shifted_x, shifted_y, shifted_z, shifted_t =
            _shifted_coordinates(x, y, z, t, nu, -1, reference)
        if shifted_x != x || shifted_y != y || shifted_z != z || shifted_t != t
            total += real(
                _plaquette_site_unchecked(
                    fields,
                    reference,
                    first_direction,
                    second_direction,
                    shifted_x,
                    shifted_y,
                    shifted_z,
                    shifted_t,
                ),
            )
        end
    end
    return total
end

function metropolis_accept(delta_action::Real, uniform_draw::Real)
    delta_value = Float64(delta_action)
    draw = Float64(uniform_draw)
    if !isfinite(delta_value)
        throw(ArgumentError("delta action must be finite"))
    end
    if !isfinite(draw) || draw < 0.0 || draw >= 1.0
        throw(ArgumentError("uniform draw must satisfy 0 <= draw < 1"))
    end
    return delta_value <= 0.0 || draw < exp(-delta_value)
end

function _fixed_link_result!(
    fields,
    updater,
    mu,
    x,
    y,
    z,
    t,
    workspace,
    su2_proposal,
    pair,
    uniform_draw,
)
    reference = _require_configuration(fields)
    nc = reference.NC
    _copy_link_to_matrix!(workspace.old_link, fields[mu], x, y, z, t)
    if nc == 2
        _small_matrix_multiply!(
            workspace.proposed_link,
            su2_proposal,
            workspace.old_link,
            2,
        )
    else
        propose_link_su3!(
            workspace.proposed_link,
            workspace.old_link,
            su2_proposal,
            pair,
            workspace.embedded,
        )
    end

    degenerate = reference.NX == 1 || reference.NY == 1 || reference.NZ == 1 || reference.NT == 1
    if degenerate
        old_plaquette_sum =
            _affected_plaquette_sum_unchecked(fields, reference, mu, x, y, z, t)
        _write_matrix_to_link!(fields[mu], workspace.proposed_link, x, y, z, t)
        new_plaquette_sum =
            _affected_plaquette_sum_unchecked(fields, reference, mu, x, y, z, t)
        delta_action =
            -(Float64(updater.beta) / nc) * (new_plaquette_sum - old_plaquette_sum)
        accepted = metropolis_accept(delta_action, uniform_draw)
        if !accepted
            _write_matrix_to_link!(fields[mu], workspace.old_link, x, y, z, t)
        end
        return MetropolisLinkResult(accepted, delta_action)
    end

    local_wilson_staple_site!(
        workspace.staple,
        fields,
        mu,
        x,
        y,
        z,
        t,
        workspace.forward,
        workspace.backward,
    )
    old_action = local_action_from_staple(workspace.old_link, workspace.staple, updater.beta)
    new_action = local_action_from_staple(workspace.proposed_link, workspace.staple, updater.beta)
    delta_action = new_action - old_action
    accepted = metropolis_accept(delta_action, uniform_draw)
    if accepted
        _write_matrix_to_link!(fields[mu], workspace.proposed_link, x, y, z, t)
    end
    return MetropolisLinkResult(accepted, delta_action)
end

function metropolis_link_fixed!(
    fields::Vector,
    updater::MetropolisUpdater,
    mu::Integer,
    x,
    y,
    z,
    t,
    workspace::MetropolisWorkspace,
    su2_proposal::AbstractMatrix,
    pair::Integer,
    uniform_draw::Real,
)
    return _fixed_link_result!(
        fields,
        updater,
        mu,
        x,
        y,
        z,
        t,
        workspace,
        su2_proposal,
        pair,
        uniform_draw,
    )
end

function metropolis_link!(
    fields::Vector,
    updater::MetropolisUpdater,
    mu::Integer,
    x,
    y,
    z,
    t,
    workspace::MetropolisWorkspace,
    rng,
    pair::Integer,
)
    make_near_identity_su2!(workspace.su2, updater.epsilon, rng)
    uniform_draw = _random_uniform(rng)
    return _fixed_link_result!(
        fields,
        updater,
        mu,
        x,
        y,
        z,
        t,
        workspace,
        workspace.su2,
        pair,
        uniform_draw,
    )
end

function metropolis_link!(fields, updater, mu, x, y, z, t; rng=nothing, pair=1)
    reference = _require_configuration(fields)
    return metropolis_link!(
        fields,
        updater,
        mu,
        x,
        y,
        z,
        t,
        MetropolisWorkspace(reference.NC),
        rng,
        pair,
    )
end

"""
    sweep!(fields, updater; rng=nothing, workspace=MetropolisWorkspace())

Offer one update to every link in site-major order: `t`, `z`, `y`, `x`, then
direction `mu`. SU(2) subgroups cycle `(1,2)`, `(2,3)`, `(1,3)`.
"""
function sweep!(
    fields::Vector,
    updater::MetropolisUpdater;
    rng=nothing,
    workspace=nothing,
)
    reference = _require_configuration(fields)
    active_workspace = workspace === nothing ? MetropolisWorkspace(reference.NC) : workspace
    accepted = 0
    offered = 0
    for t in 1:reference.NT
        for z in 1:reference.NZ
            for y in 1:reference.NY
                for x in 1:reference.NX
                    for mu in 1:4
                        offered += 1
                        pair = reference.NC == 2 ? 1 : mod(offered - 1, 3) + 1
                        result = metropolis_link!(
                            fields,
                            updater,
                            mu,
                            x,
                            y,
                            z,
                            t,
                            active_workspace,
                            rng,
                            pair,
                        )
                        accepted += ifelse(result.accepted, 1, 0)
                    end
                end
            end
        end
    end
    return MetropolisSweepResult(accepted, offered, accepted / offered)
end

function run_sweeps!(fields::Vector, updater::MetropolisUpdater, number_of_sweeps::Integer; rng=nothing)
    if number_of_sweeps < 0
        throw(ArgumentError("number_of_sweeps must be nonnegative"))
    end
    plaquette_history = Vector{Float64}(undef, number_of_sweeps)
    polyakov_history = Vector{ComplexF64}(undef, number_of_sweeps)
    acceptance_history = Vector{Float64}(undef, number_of_sweeps)
    reference = _require_configuration(fields)
    workspace = MetropolisWorkspace(reference.NC)
    total_accepted = 0
    total_offered = 0
    for sweep_index in 1:number_of_sweeps
        result = sweep!(fields, updater; rng=rng, workspace=workspace)
        total_accepted += result.accepted
        total_offered += result.offered
        plaquette_history[sweep_index] = normalized_plaquette(fields)
        polyakov_history[sweep_index] = calculate_Polyakov_loop(fields)
        acceptance_history[sweep_index] = result.acceptance_rate
    end
    return MetropolisHistory(
        plaquette_history,
        polyakov_history,
        acceptance_history,
        total_accepted,
        total_offered,
    )
end
# END src/metropolis.jl

# BEGIN src/webapi.jl
const WEB_RESULT_SCHEMA_VERSION = 2.0
const WEB_RESULT_HEADER_LENGTH = 11
const WEB_CHUNK_SCHEMA_VERSION = 1.0
const WEB_CHUNK_HEADER_LENGTH = 19
const _WEB_MAX_LATTICE_SIZE = 8
const _WEB_MAX_SWEEPS = 1000
const _WEB_MAX_SEED = 9007199254740991

"""
    WebObservables

Observables measured on one completed configuration. The slice values use
row-major display order: the first plane coordinate changes fastest.
"""
struct WebObservables
    plaquette::Float64
    polyakov::ComplexF64
    slice_width::Int64
    slice_height::Int64
    slice_values::Vector{Float64}
end

"""
    WebSimulationResult

Internal result of one browser-oriented simulation job. Convert it to the
stable flat numeric contract with [`encode_web_result`](@ref).
"""
struct WebSimulationResult
    sweeps::Int64
    plaquette_history::Vector{Float64}
    polyakov_history::Vector{ComplexF64}
    acceptance_history::Vector{Float64}
    accepted::Int64
    offered::Int64
    observables::WebObservables
    slice_frames::Vector{Float64}
end

struct WebChunkResult
    nc::Int64
    nx::Int64
    ny::Int64
    nz::Int64
    nt::Int64
    completed_sweeps::Int64
    simulation::WebSimulationResult
    rng_state::Int64
    configuration::Vector{Float64}
end

mutable struct WebGenericSession{F,W}
    nc::Int64
    nx::Int64
    ny::Int64
    nz::Int64
    nt::Int64
    fields::F
    updater::MetropolisUpdater
    rng_state::Vector{Int64}
    workspace::W
    completed_sweeps::Int64
    plane::String
    slice::Tuple{Int64,Int64}
    width::Int64
    height::Int64
    slice_buffer::Vector{Float64}
end

function _validated_web_integer(value, name, minimum, maximum)
    if !(value isa Integer)
        throw(ArgumentError("$name must be an integer"))
    end
    if value < minimum || value > maximum
        throw(ArgumentError("$name must be in $minimum:$maximum"))
    end
    return Int64(value)
end

function _validated_web_seed(seed)
    if !(seed isa Integer)
        throw(ArgumentError("seed must be an integer"))
    end
    if seed < 0 || seed > _WEB_MAX_SEED
        throw(ArgumentError("seed must be in 0:$_WEB_MAX_SEED"))
    end
    return Int64(seed)
end

function _validated_web_condition(condition)
    condition_name = lowercase(String(condition))
    if condition_name != "cold" && condition_name != "hot"
        throw(ArgumentError("condition must be \"cold\" or \"hot\""))
    end
    return condition_name
end

function web_configuration_state_length(nc, nx, ny, nz, nt)
    color_count = _validated_color_count(nc)
    nx_value = _validated_web_integer(nx, "nx", 1, _WEB_MAX_LATTICE_SIZE)
    ny_value = _validated_web_integer(ny, "ny", 1, _WEB_MAX_LATTICE_SIZE)
    nz_value = _validated_web_integer(nz, "nz", 1, _WEB_MAX_LATTICE_SIZE)
    nt_value = _validated_web_integer(nt, "nt", 1, _WEB_MAX_LATTICE_SIZE)
    return 2 * 4 * color_count * color_count * nx_value * ny_value * nz_value * nt_value
end

function encode_web_configuration(fields::Vector)
    reference = _require_configuration(fields)
    output = Vector{Float64}(
        undef,
        web_configuration_state_length(
            reference.NC,
            reference.NX,
            reference.NY,
            reference.NZ,
            reference.NT,
        ),
    )
    cursor = 0
    for mu in 1:4
        field = fields[mu]
        for t in 1:reference.NT
            for z in 1:reference.NZ
                for y in 1:reference.NY
                    for x in 1:reference.NX
                        for j in 1:reference.NC
                            for i in 1:reference.NC
                                value = field[i, j, x, y, z, t]
                                output[cursor + 1] = real(value)
                                output[cursor + 2] = imag(value)
                                cursor += 2
                            end
                        end
                    end
                end
            end
        end
    end
    return output
end

function decode_web_configuration(nc, nx, ny, nz, nt, state::AbstractVector)
    expected_length = web_configuration_state_length(nc, nx, ny, nz, nt)
    if length(state) != expected_length
        throw(DimensionMismatch("configuration state length must equal $expected_length"))
    end
    fields = Initialize_4DGaugefields(nc, 0, nx, ny, nz, nt; condition="cold")
    cursor = 0
    for mu in 1:4
        field = fields[mu]
        for t in 1:field.NT
            for z in 1:field.NZ
                for y in 1:field.NY
                    for x in 1:field.NX
                        for j in 1:field.NC
                            for i in 1:field.NC
                                real_part = Float64(state[cursor + 1])
                                imaginary_part = Float64(state[cursor + 2])
                                if !isfinite(real_part) || !isfinite(imaginary_part)
                                    throw(ArgumentError("configuration state must be finite"))
                                end
                                field[i, j, x, y, z, t] = ComplexF64(real_part, imaginary_part)
                                cursor += 2
                            end
                        end
                    end
                end
            end
        end
    end
    return fields
end

function _initialize_web_configuration(nc, nx, ny, nz, nt, condition, rng_state)
    fields = Initialize_4DGaugefields(nc, 0, nx, ny, nz, nt; condition="cold")
    if condition == "cold"
        return fields
    end
    matrix = zeros(ComplexF64, nc, nc)
    for mu in 1:4
        field = fields[mu]
        for t in 1:nt
            for z in 1:nz
                for y in 1:ny
                    for x in 1:nx
                        for j in 1:nc
                            for i in 1:nc
                                real_part, imaginary_part = web_standard_normal_pair!(rng_state)
                                matrix[i, j] = ComplexF64(real_part, imaginary_part)
                            end
                        end
                        normalizeN!(matrix)
                        for j in 1:nc
                            for i in 1:nc
                                field[i, j, x, y, z, t] = matrix[i, j]
                            end
                        end
                    end
                end
            end
        end
    end
    return fields
end

"""
    run_observables_on_configuration(fields; plane="xy", slice=(1, 1))

Measure the final normalized plaquette, complex Polyakov loop, and one local
plaquette-energy slice without exposing gauge-field objects to JavaScript.
"""
function run_observables_on_configuration(fields; plane="xy", slice=(1, 1))
    reference = _require_configuration(fields)
    width, height = slice_shape(fields, plane)
    slice_values = zeros(Float64, width * height)
    local_plaquette_energy!(slice_values, fields, plane, slice)
    return WebObservables(
        normalized_plaquette(fields),
        calculate_Polyakov_loop(fields),
        Int64(width),
        Int64(height),
        slice_values,
    )
end

function _copy_slice_frame!(frames, frame_index, frame_size, fields, plane, slice, buffer)
    local_plaquette_energy!(buffer, fields, plane, slice)
    offset = (frame_index - 1) * frame_size
    for index in 1:frame_size
        frames[offset + index] = buffer[index]
    end
    return frames
end

"""
    run_simulation(nx, ny, nz, nt, beta, number_of_sweeps, seed; kwargs...)
    run_simulation(lattice_size, beta, number_of_sweeps, seed; kwargs...)

Run a complete SU(3) Metropolis job in one Julia call. The public v0.1 path is
serial and bounded to avoid accidental unbounded browser allocations. The
four-extent method supports anisotropic lattices; the scalar method is the
backward-compatible cubic shortcut.
"""
function run_simulation(
    nx,
    ny,
    nz,
    nt,
    beta,
    number_of_sweeps,
    seed;
    epsilon=0.2,
    condition="cold",
    plane="xy",
    slice=(1, 1),
)
    nx_value = _validated_web_integer(nx, "nx", 1, _WEB_MAX_LATTICE_SIZE)
    ny_value = _validated_web_integer(ny, "ny", 1, _WEB_MAX_LATTICE_SIZE)
    nz_value = _validated_web_integer(nz, "nz", 1, _WEB_MAX_LATTICE_SIZE)
    nt_value = _validated_web_integer(nt, "nt", 1, _WEB_MAX_LATTICE_SIZE)
    sweep_count =
        _validated_web_integer(number_of_sweeps, "number_of_sweeps", 0, _WEB_MAX_SWEEPS)
    seed_value = _validated_web_seed(seed)
    condition_name = _validated_web_condition(condition)
    updater = MetropolisUpdater(beta, epsilon)

    Random.seed!(seed_value)
    fields = Initialize_4DGaugefields(
        3,
        0,
        nx_value,
        ny_value,
        nz_value,
        nt_value;
        condition=condition_name,
    )
    width, height = slice_shape(fields, plane)
    frame_size = width * height
    slice_frames = Vector{Float64}(undef, (sweep_count + 1) * frame_size)
    slice_buffer = zeros(Float64, frame_size)
    _copy_slice_frame!(slice_frames, 1, frame_size, fields, plane, slice, slice_buffer)

    plaquette_history = Vector{Float64}(undef, sweep_count)
    polyakov_history = Vector{ComplexF64}(undef, sweep_count)
    acceptance_history = Vector{Float64}(undef, sweep_count)
    workspace = MetropolisWorkspace()
    total_accepted = 0
    total_offered = 0
    for sweep_index in 1:sweep_count
        update_result = sweep!(fields, updater; workspace=workspace)
        total_accepted += update_result.accepted
        total_offered += update_result.offered
        plaquette_history[sweep_index] = normalized_plaquette(fields)
        polyakov_history[sweep_index] = calculate_Polyakov_loop(fields)
        acceptance_history[sweep_index] = update_result.acceptance_rate
        _copy_slice_frame!(
            slice_frames,
            sweep_index + 1,
            frame_size,
            fields,
            plane,
            slice,
            slice_buffer,
        )
    end

    history = MetropolisHistory(
        plaquette_history,
        polyakov_history,
        acceptance_history,
        total_accepted,
        total_offered,
    )
    final_plaquette = sweep_count == 0 ? normalized_plaquette(fields) : plaquette_history[sweep_count]
    final_polyakov =
        sweep_count == 0 ? calculate_Polyakov_loop(fields) : polyakov_history[sweep_count]
    final_slice = copy(slice_buffer)
    observables = WebObservables(
        final_plaquette,
        final_polyakov,
        Int64(width),
        Int64(height),
        final_slice,
    )
    return WebSimulationResult(
        sweep_count,
        history.plaquette,
        history.polyakov,
        history.acceptance,
        history.accepted,
        history.offered,
        observables,
        slice_frames,
    )
end

function run_simulation(
    lattice_size,
    beta,
    number_of_sweeps,
    seed;
    epsilon=0.2,
    condition="cold",
    plane="xy",
    slice=(1, 1),
)
    return run_simulation(
        lattice_size,
        lattice_size,
        lattice_size,
        lattice_size,
        beta,
        number_of_sweeps,
        seed;
        epsilon=epsilon,
        condition=condition,
        plane=plane,
        slice=slice,
    )
end

function _validate_web_result(result::WebSimulationResult)
    sweep_count = result.sweeps
    if sweep_count < 0 ||
       length(result.plaquette_history) != sweep_count ||
       length(result.polyakov_history) != sweep_count ||
       length(result.acceptance_history) != sweep_count
        throw(ArgumentError("history lengths must equal the sweep count"))
    end
    if result.accepted < 0 || result.offered < 0 || result.accepted > result.offered
        throw(ArgumentError("accepted/offered counts are inconsistent"))
    end
    observables = result.observables
    frame_count = sweep_count + 1
    frame_size = observables.slice_width * observables.slice_height
    if observables.slice_width <= 0 || observables.slice_height <= 0 ||
       length(observables.slice_values) !=
       frame_size ||
       length(result.slice_frames) != frame_count * frame_size
        throw(ArgumentError("slice metadata and values are inconsistent"))
    end
    final_offset = (frame_count - 1) * frame_size
    for index in 1:frame_size
        if result.slice_frames[final_offset + index] != observables.slice_values[index]
            throw(ArgumentError("the final slice frame must match the final observables"))
        end
    end
    return nothing
end

"""
    encode_web_result(result)

Encode a simulation result as a `Vector{Float64}`. Schema version 2 layout:

```text
[schema, sweeps, final_plaquette, final_polyakov_re, final_polyakov_im,
 overall_acceptance, accepted, offered, slice_width, slice_height, frame_count,
 plaquette_history...,
 polyakov_real_history...,
 polyakov_imag_history...,
 acceptance_history...,
 slice_frames...]
```
"""
function encode_web_result(result::WebSimulationResult)
    _validate_web_result(result)
    sweep_count = result.sweeps
    observables = result.observables
    output_length =
        WEB_RESULT_HEADER_LENGTH + 4 * sweep_count + length(result.slice_frames)
    output = Vector{Float64}(undef, output_length)

    output[1] = WEB_RESULT_SCHEMA_VERSION
    output[2] = sweep_count
    output[3] = observables.plaquette
    output[4] = real(observables.polyakov)
    output[5] = imag(observables.polyakov)
    output[6] = result.offered == 0 ? 0.0 : result.accepted / result.offered
    output[7] = result.accepted
    output[8] = result.offered
    output[9] = observables.slice_width
    output[10] = observables.slice_height
    output[11] = sweep_count + 1

    offset = WEB_RESULT_HEADER_LENGTH
    for index in 1:sweep_count
        output[offset + index] = result.plaquette_history[index]
    end
    offset += sweep_count
    for index in 1:sweep_count
        output[offset + index] = real(result.polyakov_history[index])
    end
    offset += sweep_count
    for index in 1:sweep_count
        output[offset + index] = imag(result.polyakov_history[index])
    end
    offset += sweep_count
    for index in 1:sweep_count
        output[offset + index] = result.acceptance_history[index]
    end
    offset += sweep_count
    for index in 1:length(result.slice_frames)
        output[offset + index] = result.slice_frames[index]
    end
    return output
end

function run_simulation_chunk(
    nc,
    nx,
    ny,
    nz,
    nt,
    beta,
    chunk_sweeps,
    seed_or_rng_state,
    completed_sweeps,
    configuration::AbstractVector;
    epsilon=0.2,
    condition="cold",
    plane="xy",
    slice=(1, 1),
)
    color_count = _validated_color_count(nc)
    nx_value = _validated_web_integer(nx, "nx", 1, _WEB_MAX_LATTICE_SIZE)
    ny_value = _validated_web_integer(ny, "ny", 1, _WEB_MAX_LATTICE_SIZE)
    nz_value = _validated_web_integer(nz, "nz", 1, _WEB_MAX_LATTICE_SIZE)
    nt_value = _validated_web_integer(nt, "nt", 1, _WEB_MAX_LATTICE_SIZE)
    sweep_count = _validated_web_integer(chunk_sweeps, "chunk_sweeps", 0, _WEB_MAX_SWEEPS)
    completed = _validated_web_integer(completed_sweeps, "completed_sweeps", 0, _WEB_MAX_SWEEPS)
    if completed + sweep_count > _WEB_MAX_SWEEPS
        throw(ArgumentError("completed_sweeps + chunk_sweeps must not exceed $_WEB_MAX_SWEEPS"))
    end
    condition_name = _validated_web_condition(condition)
    updater = MetropolisUpdater(beta, epsilon)

    first_chunk = isempty(configuration)
    if first_chunk && completed != 0
        throw(ArgumentError("an empty configuration requires completed_sweeps = 0"))
    end
    rng_state = if first_chunk
        web_rng_state(_validated_web_seed(seed_or_rng_state))
    else
        restore_web_rng_state(seed_or_rng_state)
    end
    fields = if first_chunk
        _initialize_web_configuration(
            color_count,
            nx_value,
            ny_value,
            nz_value,
            nt_value,
            condition_name,
            rng_state,
        )
    else
        decode_web_configuration(
            color_count,
            nx_value,
            ny_value,
            nz_value,
            nt_value,
            configuration,
        )
    end

    width, height = slice_shape(fields, plane)
    frame_size = width * height
    slice_frames = Vector{Float64}(undef, (sweep_count + 1) * frame_size)
    slice_buffer = zeros(Float64, frame_size)
    _copy_slice_frame!(slice_frames, 1, frame_size, fields, plane, slice, slice_buffer)

    plaquette_history = Vector{Float64}(undef, sweep_count)
    polyakov_history = Vector{ComplexF64}(undef, sweep_count)
    acceptance_history = Vector{Float64}(undef, sweep_count)
    workspace = MetropolisWorkspace(color_count)
    total_accepted = 0
    total_offered = 0
    for sweep_index in 1:sweep_count
        update_result = sweep!(fields, updater; rng=rng_state, workspace=workspace)
        total_accepted += update_result.accepted
        total_offered += update_result.offered
        plaquette_history[sweep_index] = normalized_plaquette(fields)
        polyakov_history[sweep_index] = calculate_Polyakov_loop(fields)
        acceptance_history[sweep_index] = update_result.acceptance_rate
        _copy_slice_frame!(
            slice_frames,
            sweep_index + 1,
            frame_size,
            fields,
            plane,
            slice,
            slice_buffer,
        )
    end

    final_plaquette = sweep_count == 0 ? normalized_plaquette(fields) : plaquette_history[sweep_count]
    final_polyakov =
        sweep_count == 0 ? calculate_Polyakov_loop(fields) : polyakov_history[sweep_count]
    final_slice = copy(slice_buffer)
    observables = WebObservables(
        final_plaquette,
        final_polyakov,
        Int64(width),
        Int64(height),
        final_slice,
    )
    simulation = WebSimulationResult(
        sweep_count,
        plaquette_history,
        polyakov_history,
        acceptance_history,
        total_accepted,
        total_offered,
        observables,
        slice_frames,
    )
    return WebChunkResult(
        color_count,
        nx_value,
        ny_value,
        nz_value,
        nt_value,
        completed + sweep_count,
        simulation,
        rng_state[1],
        encode_web_configuration(fields),
    )
end

function encode_web_chunk_result(result::WebChunkResult)
    simulation = result.simulation
    _validate_web_result(simulation)
    sweep_count = simulation.sweeps
    observables = simulation.observables
    output_length = WEB_CHUNK_HEADER_LENGTH +
                    4 * sweep_count +
                    length(simulation.slice_frames) +
                    length(result.configuration)
    output = Vector{Float64}(undef, output_length)
    output[1] = WEB_CHUNK_SCHEMA_VERSION
    output[2] = result.nc
    output[3] = result.nx
    output[4] = result.ny
    output[5] = result.nz
    output[6] = result.nt
    output[7] = sweep_count
    output[8] = result.completed_sweeps
    output[9] = observables.plaquette
    output[10] = real(observables.polyakov)
    output[11] = imag(observables.polyakov)
    output[12] = simulation.offered == 0 ? 0.0 : simulation.accepted / simulation.offered
    output[13] = simulation.accepted
    output[14] = simulation.offered
    output[15] = observables.slice_width
    output[16] = observables.slice_height
    output[17] = sweep_count + 1
    output[18] = result.rng_state
    output[19] = length(result.configuration)

    offset = WEB_CHUNK_HEADER_LENGTH
    for value in simulation.plaquette_history
        offset += 1
        output[offset] = value
    end
    for value in simulation.polyakov_history
        offset += 1
        output[offset] = real(value)
    end
    for value in simulation.polyakov_history
        offset += 1
        output[offset] = imag(value)
    end
    for value in simulation.acceptance_history
        offset += 1
        output[offset] = value
    end
    for value in simulation.slice_frames
        offset += 1
        output[offset] = value
    end
    for value in result.configuration
        offset += 1
        output[offset] = value
    end
    return output
end

function start_web_simulation_session(
    nc,
    nx,
    ny,
    nz,
    nt,
    beta,
    seed;
    epsilon=0.2,
    condition="cold",
    plane="xy",
    slice=(1, 1),
    low_precision=false,
)
    color_count = _validated_color_count(nc)
    nx_value = _validated_web_integer(nx, "nx", 1, _WEB_MAX_LATTICE_SIZE)
    ny_value = _validated_web_integer(ny, "ny", 1, _WEB_MAX_LATTICE_SIZE)
    nz_value = _validated_web_integer(nz, "nz", 1, _WEB_MAX_LATTICE_SIZE)
    nt_value = _validated_web_integer(nt, "nt", 1, _WEB_MAX_LATTICE_SIZE)
    seed_value = _validated_web_seed(seed)
    condition_name = _validated_web_condition(condition)
    updater = MetropolisUpdater(beta, epsilon)
    first_axis, second_axis, first_fixed_axis, second_fixed_axis = _plane_axes(plane)
    extents = (nx_value, ny_value, nz_value, nt_value)
    fixed_slice = _validated_slice(slice, first_fixed_axis, second_fixed_axis, extents)

    if color_count == 2 && nx_value > 1 && ny_value > 1 && nz_value > 1 && nt_value > 1
        return start_fast_su2_web_session(
            nx_value,
            ny_value,
            nz_value,
            nt_value,
            updater.beta,
            seed_value;
            epsilon=updater.epsilon,
            condition=condition_name,
            plane=plane,
            slice=fixed_slice,
            low_precision=low_precision,
        )
    end

    rng_state = web_rng_state(seed_value)
    fields = _initialize_web_configuration(
        color_count,
        nx_value,
        ny_value,
        nz_value,
        nt_value,
        condition_name,
        rng_state,
    )
    width = extents[first_axis]
    height = extents[second_axis]
    return WebGenericSession(
        color_count,
        nx_value,
        ny_value,
        nz_value,
        nt_value,
        fields,
        updater,
        rng_state,
        MetropolisWorkspace(color_count),
        0,
        String(plane),
        fixed_slice,
        Int64(width),
        Int64(height),
        zeros(Float64, width * height),
    )
end

function run_web_session_chunk!(session::WebGenericSession, chunk_sweeps)
    sweep_count = _validated_web_integer(chunk_sweeps, "chunk_sweeps", 0, _WEB_MAX_SWEEPS)
    if session.completed_sweeps + sweep_count > _WEB_MAX_SWEEPS
        throw(ArgumentError("cumulative sweep count must not exceed $_WEB_MAX_SWEEPS"))
    end
    frame_size = session.width * session.height
    frames = Vector{Float64}(undef, (sweep_count + 1) * frame_size)
    _copy_slice_frame!(
        frames,
        1,
        frame_size,
        session.fields,
        session.plane,
        session.slice,
        session.slice_buffer,
    )
    plaquette_history = Vector{Float64}(undef, sweep_count)
    polyakov_history = Vector{ComplexF64}(undef, sweep_count)
    acceptance_history = Vector{Float64}(undef, sweep_count)
    accepted_total = 0
    offered_total = 0
    for sweep_index in 1:sweep_count
        update_result = sweep!(
            session.fields,
            session.updater;
            rng=session.rng_state,
            workspace=session.workspace,
        )
        accepted_total += update_result.accepted
        offered_total += update_result.offered
        plaquette_history[sweep_index] = normalized_plaquette(session.fields)
        polyakov_history[sweep_index] = calculate_Polyakov_loop(session.fields)
        acceptance_history[sweep_index] = update_result.acceptance_rate
        _copy_slice_frame!(
            frames,
            sweep_index + 1,
            frame_size,
            session.fields,
            session.plane,
            session.slice,
            session.slice_buffer,
        )
    end
    final_plaquette =
        sweep_count == 0 ? normalized_plaquette(session.fields) : plaquette_history[sweep_count]
    final_polyakov =
        sweep_count == 0 ? calculate_Polyakov_loop(session.fields) : polyakov_history[sweep_count]
    session.completed_sweeps += sweep_count
    simulation = WebSimulationResult(
        sweep_count,
        plaquette_history,
        polyakov_history,
        acceptance_history,
        accepted_total,
        offered_total,
        WebObservables(
            final_plaquette,
            final_polyakov,
            session.width,
            session.height,
            copy(session.slice_buffer),
        ),
        frames,
    )
    output = encode_web_chunk_result(
        WebChunkResult(
            session.nc,
            session.nx,
            session.ny,
            session.nz,
            session.nt,
            session.completed_sweeps,
            simulation,
            session.rng_state[1],
            Float64[],
        ),
    )
    output[1] = 2.0
    return output
end

function run_simulation_chunk_web(
    nc,
    nx,
    ny,
    nz,
    nt,
    beta,
    chunk_sweeps,
    seed_or_rng_state,
    completed_sweeps,
    configuration::AbstractVector;
    epsilon=0.2,
    condition="cold",
    plane="xy",
    slice=(1, 1),
)
    color_count = _validated_color_count(nc)
    nx_value = _validated_web_integer(nx, "nx", 1, _WEB_MAX_LATTICE_SIZE)
    ny_value = _validated_web_integer(ny, "ny", 1, _WEB_MAX_LATTICE_SIZE)
    nz_value = _validated_web_integer(nz, "nz", 1, _WEB_MAX_LATTICE_SIZE)
    nt_value = _validated_web_integer(nt, "nt", 1, _WEB_MAX_LATTICE_SIZE)
    sweep_count = _validated_web_integer(chunk_sweeps, "chunk_sweeps", 0, _WEB_MAX_SWEEPS)
    completed = _validated_web_integer(completed_sweeps, "completed_sweeps", 0, _WEB_MAX_SWEEPS)
    if completed + sweep_count > _WEB_MAX_SWEEPS
        throw(ArgumentError("completed_sweeps + chunk_sweeps must not exceed $_WEB_MAX_SWEEPS"))
    end
    condition_name = _validated_web_condition(condition)
    updater = MetropolisUpdater(beta, epsilon)
    first_chunk = isempty(configuration)
    if first_chunk && completed != 0
        throw(ArgumentError("an empty configuration requires completed_sweeps = 0"))
    end

    if color_count == 2 && nx_value > 1 && ny_value > 1 && nz_value > 1 && nt_value > 1
        rng_value = if first_chunk
            _validated_web_seed(seed_or_rng_state)
        else
            restore_web_rng_state(seed_or_rng_state)[1]
        end
        first_axis, second_axis, first_fixed_axis, second_fixed_axis = _plane_axes(plane)
        extents = (nx_value, ny_value, nz_value, nt_value)
        fixed_slice = _validated_slice(slice, first_fixed_axis, second_fixed_axis, extents)
        return run_fast_su2_chunk_web(
            nx_value,
            ny_value,
            nz_value,
            nt_value,
            updater.beta,
            sweep_count,
            rng_value,
            completed,
            configuration;
            epsilon=updater.epsilon,
            condition=condition_name,
            plane=plane,
            slice=fixed_slice,
        )
    end

    return encode_web_chunk_result(
        run_simulation_chunk(
            color_count,
            nx_value,
            ny_value,
            nz_value,
            nt_value,
            updater.beta,
            sweep_count,
            seed_or_rng_state,
            completed,
            configuration;
            epsilon=updater.epsilon,
            condition=condition_name,
            plane=plane,
            slice=slice,
        ),
    )
end

"""
    run_simulation_web(nx, ny, nz, nt, beta, number_of_sweeps, seed; kwargs...)
    run_simulation_web(lattice_size, beta, number_of_sweeps, seed; kwargs...)

One-shot browser entrypoint that initializes, updates, measures, and returns
only the flat numeric schema accepted by `run_from_source_typed`.
"""
function run_simulation_web(
    nx,
    ny,
    nz,
    nt,
    beta,
    number_of_sweeps,
    seed;
    epsilon=0.2,
    condition="cold",
    plane="xy",
    slice=(1, 1),
)
    result = run_simulation(
        nx,
        ny,
        nz,
        nt,
        beta,
        number_of_sweeps,
        seed;
        epsilon=epsilon,
        condition=condition,
        plane=plane,
        slice=slice,
    )
    return encode_web_result(result)
end


function run_simulation_web(
    lattice_size,
    beta,
    number_of_sweeps,
    seed;
    epsilon=0.2,
    condition="cold",
    plane="xy",
    slice=(1, 1),
)
    return run_simulation_web(
        lattice_size,
        lattice_size,
        lattice_size,
        lattice_size,
        beta,
        number_of_sweeps,
        seed;
        epsilon=epsilon,
        condition=condition,
        plane=plane,
        slice=slice,
    )
end
# END src/webapi.jl
